# Generated by Django 4.2.6 on 2023-11-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_books_picture_alter_books_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='picture',
            new_name='image',
        ),
    ]
