# Generated by Django 4.2.6 on 2023-11-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_picture_books_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='image',
            new_name='picture',
        ),
    ]
